version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:3000"
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4000:3000"
    depends_on:
      - frontend
    restart: always
    volumes:
      - ./client/dist:/app/client/dist
